apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hl-cardconjurer-ingress
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: jam.jelly.card
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hl-cardconjurer-service
                port:
                  number: 80